Repository GaloisInc/grease, pull requests merged in 2025-04, with the labels that each got.

#78 Dockerfile: Allow building with `podman`
  Dockerfile
Labels: infrastructure/ci

#86 doc: Describe which C undefined behaviors GREASE supports
  doc/SUMMARY.md
  doc/limitations.md
  doc/requirements.md
  doc/undefined-behavior.md
Labels: documentation

#89 ci: Upgrade to the latest Cabal version
  .github/workflows/ci.yaml
  Dockerfile
Labels: infrastructure/ci

#97 oughta: Rename from FileCheck
  .github/workflows/ci.yaml
  .github/workflows/lint.yml
  cabal.project
  doc/dev.md
  grease-cli/grease-cli.cabal
  grease-cli/tests/Main.hs
  oughta/LICENSE
  oughta/README.md
  oughta/oughta.cabal
  oughta/src/Oughta.hs
  oughta/src/Oughta/Exception.hs
  oughta/src/Oughta/Extract.hs
  oughta/src/Oughta/Lua.hs
  oughta/src/Oughta/LuaApi.hs
  oughta/src/Oughta/Pos.hs
  oughta/src/Oughta/Result.hs
  oughta/src/Oughta/Traceback.hs
  oughta/src/Oughta/oughta.lua
  oughta/test-data/.gitignore
  oughta/test-data/fail/check.txt
  oughta/test-data/fail/here.txt
  oughta/test-data/pass/check-empty.txt
  oughta/test-data/pass/check-immediate.txt
  oughta/test-data/pass/check.txt
  oughta/test-data/pass/file.txt
  oughta/test-data/pass/for.txt
  oughta/test-data/pass/function.txt
  oughta/test-data/pass/here.txt
  oughta/test-data/pass/hereln.txt
  oughta/test-data/pass/line.txt
  oughta/test-data/pass/prelude.txt
  oughta/test-data/pass/source-map.txt
  oughta/test-data/pass/src-line.txt
  oughta/test-data/pass/text.txt
  oughta/test-data/pass/unicode.txt
  oughta/test-data/pass/var.txt
  oughta/test/Test.hs
Labels: filecheck

#102 `elf-edit-core-dump`: Export more decoding functions
  elf-edit-core-dump/src/Data/ElfEdit/CoreDump.hs
Labels: elf-edit-core-dump

#104 Switch to Hackage version of Oughta
  .github/workflows/ci.yaml
  .github/workflows/lint.yml
  cabal.project
  doc/dev.md
  oughta/LICENSE
  oughta/README.md
  oughta/oughta.cabal
  oughta/src/Oughta.hs
  oughta/src/Oughta/Exception.hs
  oughta/src/Oughta/Extract.hs
  oughta/src/Oughta/Lua.hs
  oughta/src/Oughta/LuaApi.hs
  oughta/src/Oughta/Pos.hs
  oughta/src/Oughta/Result.hs
  oughta/src/Oughta/Traceback.hs
  oughta/src/Oughta/oughta.lua
  oughta/test-data/.gitignore
  oughta/test-data/fail/check.txt
  oughta/test-data/fail/here.txt
  oughta/test-data/pass/check-empty.txt
  oughta/test-data/pass/check-immediate.txt
  oughta/test-data/pass/check.txt
  oughta/test-data/pass/file.txt
  oughta/test-data/pass/for.txt
  oughta/test-data/pass/function.txt
  oughta/test-data/pass/here.txt
  oughta/test-data/pass/hereln.txt
  oughta/test-data/pass/line.txt
  oughta/test-data/pass/prelude.txt
  oughta/test-data/pass/source-map.txt
  oughta/test-data/pass/src-line.txt
  oughta/test-data/pass/text.txt
  oughta/test-data/pass/unicode.txt
  oughta/test-data/pass/var.txt
  oughta/test/Test.hs
  oughta/test/test.lua
Labels: oughta
