Repository GaloisInc/grease, pull requests merged in 2025-03, with the labels that each got.

#60 README: Refer to the blog post
  README.md
Labels: documentation

#61 doc: Add GitHub URL to mdBook output
  doc/book.toml
Labels: documentation

#63 Revert "CI: Disable ubuntu-22.04-arm Docker job for now"
  .github/workflows/docker.yml
Labels: infrastructure/ci

#66 Docker: Properly initialize `grease.buildinfo.json`
  .github/ci.sh
  .github/workflows/docker.yml
Labels: infrastructure/ci

#67 Remove `ArchRepr`
  src/Grease/Macaw/Arch.hs
  src/Grease/Macaw/Arch/AArch32.hs
  src/Grease/Macaw/Arch/PPC32.hs
  src/Grease/Macaw/Arch/PPC64.hs
  src/Grease/Macaw/Arch/X86.hs
  src/Grease/Macaw/ResolveCall.hs
Labels: tech debt

#68 Support more `SymbolReloc`s (e.g., `R_X86_64_64`)
  src/Grease/Macaw.hs
  src/Grease/Macaw/Arch.hs
  src/Grease/Macaw/Arch/AArch32.hs
  src/Grease/Macaw/Arch/PPC32.hs
  src/Grease/Macaw/Arch/PPC64.hs
  src/Grease/Macaw/Arch/X86.hs
  src/Grease/Macaw/Load/Relocation.hs
  src/Grease/Macaw/PLT.hs
  src/Grease/Main.hs
Labels: relocations
