Repository GaloisInc/grease, pull requests merged in 2025-05, with the labels that each got.

#142 ci: Check for stale TODOs
  .github/workflows/lint.yml
  scripts/lint/stale-todo.py
Labels: infrastructure/ci

#148 `doc/overrides.md`: List LLVM-exclusive overrides properly
  doc/overrides.md
  doc/scripts/get-overrides.sh
Labels: documentation

#155 doc: Split section on built-in overrides into its own page
  doc/SUMMARY.md
  doc/builtins.md
  doc/overrides.md
Labels: documentation

#173 ci: Lint and check formatting of Ghidra script
  .github/workflows/lint.yml
  doc/dev.md
  ghidra_scripts/grease.py
Labels: infrastructure/ci

#174 ci: Build with `--semaphore`
  .github/workflows/ci.yaml
Labels: infrastructure/ci

#183 doc: Add documentation on regular maintenance tasks
  doc/dev.md
Labels: documentation

#194 Remove imports from prelude, fix up conflicts/unused imports
  grease/src/Grease/AssertProperty.hs
  grease/src/Grease/BranchTracer.hs
  grease/src/Grease/Cursor/List.hs
  grease/src/Grease/Diagnostic.hs
  grease/src/Grease/FunctionOverride.hs
  grease/src/Grease/Heuristic.hs
  grease/src/Grease/LLVM/Overrides.hs
  grease/src/Grease/Macaw.hs
  grease/src/Grease/Macaw/FunctionOverride.hs
  grease/src/Grease/Macaw/Load.hs
  grease/src/Grease/Macaw/Load/Relocation.hs
  grease/src/Grease/Macaw/Memory.hs
  grease/src/Grease/Macaw/PLT.hs
  grease/src/Grease/Macaw/Syscall.hs
  grease/src/Grease/Shape/Concretize.hs
  grease/src/Grease/Shape/Parse.hs
  grease/src/Grease/Shape/Pointer.hs
  grease/src/Grease/Shape/Print.hs
  grease/src/Grease/Solver.hs
  grease/src/Grease/Syscall.hs
  grease/src/Grease/Time.hs
  grease/src/Grease/Utility.hs
Labels: topic/tech debt, type/refactor

#198 llvm: Include filesystem `root` directory
  grease-cli/tests/llvm/extra/fs/root/.gitkeep
Labels: area/lang/llvm
