Repository GaloisInc/grease, pull requests merged in 2025-06, with the labels that each got.

#214 Disable `-Werror=prepositive-qualified-module` in Cabal files
  grease-aarch32/grease-aarch32.cabal
  grease-cli/grease-cli.cabal
  grease-ppc/grease-ppc.cabal
  grease-x86/grease-x86.cabal
  grease/grease.cabal
Labels: area/infra/ci

#222 Fix a panic involving `fresh-bytes`
  grease/src/Grease/Concretize/ToConcretize.hs
  grease/src/Grease/Refine.hs
Labels: type/bug, area/concretization

#233 `Grease.Shape.Parse`: Allow parsing exact bytes with RLE
  doc/shape-dsl.md
  grease-cli/tests/Shape.hs
  grease/src/Grease/Shape/Parse.hs
Labels: area/shapes dsl
